class CheckMailmapTest < Minitest::Test
  private

  EXECUTABLE_PATH: String

  def check_mailmap: (*untyped args, ?mailmap_path: String, ?stdin_data: String?) -> [String, String, Process::Status]
end

# https://github.com/ruby/rbs/blob/v3.8.1/stdlib/open3/0/open3.rbs
module Open3
  def self.capture3: (*untyped args) -> [String, String, Process::Status]
end
